"""Initial migration

Revision ID: eb8e79bfbfa4
Revises: 
Create Date: 2025-02-28 15:54:32.654589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8e79bfbfa4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('event_date', sa.DATE(), nullable=True),
    sa.Column('event_name', sa.VARCHAR(), nullable=False),
    sa.Column('expected_audience', sa.INTEGER(), nullable=True),
    sa.Column('fees', sa.FLOAT(), nullable=True),
    sa.Column('institute_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_paid_event', sa.BOOLEAN(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), nullable=True),
    sa.Column('travel_accomodation', sa.VARCHAR(), nullable=True),
    sa.Column('website', sa.VARCHAR(), nullable=True),
    sa.Column('attachments', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    # ### end Alembic commands ###
