name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alembic gunicorn

      - name: Set Environment Variables
        run: |
          echo "ENV=production" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> $GITHUB_ENV
          echo "Google_maps_key=${{ secrets.Google_maps_key }}" >> $GITHUB_ENV
          echo "FILE_AWS_S3_BUCKET=${{ secrets.FILE_AWS_S3_BUCKET }}" >> $GITHUB_ENV

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/fastapi-backend
            git pull origin main
            # Activate virtual environment (adjust path if needed)
            source venv/bin/activate
            pip install -r requirements.txt
            export SECRET_KEY='${{ secrets.SECRET_KEY }}'
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
            export Google_maps_key=${{ secrets.Google_maps_key }}
            export FILE_AWS_S3_BUCKET=${{ secrets.FILE_AWS_S3_BUCKET }}
            export TASKS_FILE_AWS_S3_BUCKET=${{ secrets.TASKS_FILE_AWS_S3_BUCKET }}
            alembic upgrade head
            sudo systemctl restart fastapi
